[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
internetarchive = "^5.0.5"
gitpython = "^3.1.43"
markdown2 = "^2.5.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
